server:
  port: 8083

spring:
  application:
    name: "Order Service"
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: false
    change-log: classpath:/db.changelog/changelog-master.xml

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api/order/swagger-ui.html